config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'profile/show' => 'users#show', as: 'show_profile'
  get 'profile/edit' => 'users#edit', as: 'edit_profile'
  match 'profile/update' => 'users#update', as: 'update_profile', via: [:patch]

  get 'admin/list_users' => 'admin#list_users', as: 'admin_list_users'
  get 'admin/show_user' => 'admin#show_user', as: 'admin_show_user'
  get 'admin/edit_user/:id' => 'admin#edit_user', as: 'admin_edit_user'
  match 'admin/update_user/:id' => 'admin#update_user', as: 'admin_update_user', via: [:patch]
  match 'admin/delete_user/:id' => 'admin#delete_user', as: 'admin_delete_user', via: [:delete]

  resources :wallets

  resources :groups do
    member do
      get 'logo'
    end
  end

  resources :store_infos do
    resources :tags
    resources :store_info_ratings

    member do
      get 'logo'
    end
  end

  resources :agents
  resources :card_types
  resources :card_levels
  resources :banks
  resources :cards do
    resources :tags
    resources :card_ratings
  end

  resources :discounts do
    resources :tags
    resources :discount_ratings
  end

  root to: "welcome#index"
end

app/models/store_info.rb
class StoreInfo < ActiveRecord::Base
    has_many :group_sets, dependent: :destroy
    has_many :groups, :through => :group_sets
    
    has_many :store_info_ratings, dependent: :destroy
    has_many :users, :through => :store_info_ratings

    has_many :tag_sets, dependent: :destroy
    has_many :tags, :through => :tag_sets

    validates :name, presence: true
end

app/controllers/store_infos_controller.rb
class StoreInfosController < ApplicationController
    def new
        if current_user.nil?
            redirect_to store_infos_path
        end

        @store_info = StoreInfo.new
        @groups = Group.all
        @group = Group.new
    end

    def create
        
        @store_info_update_data = store_info_params
        @store_info_update_data['photo'] = nil
        @store_info = StoreInfo.new(@store_info_update_data)
        ## save to get id
        unless @store_info.save
            render 'new'
        end

        ## store logo
        @store_info_update_data = store_info_params
        unless params[:store_info][:photo].nil?
            ## rename figure to avoid overwrite
            if params[:store_info][:photo].original_filename =~ /.*\.(.*)/
                @file_name = "id" + @store_info.id.to_s + "." + $1
            else
                @file_name = "id" + @store_info.id.to_s + "." + params[:store_info][:photo].original_filename
            end

            @stored_file_path = Rails.root.join('public', 'photo', 'store_infos', @file_name)
            File.open(@stored_file_path, 'wb') do |file|
                file.write(params[:store_info][:photo].read)
            end

            @store_info_update_data['photo'] = @file_name
        end

        ## group
        @group_update_data = group_params
        @group_update_data['photo'] = nil
        @group = Group.new(@group_update_data)
        
        @group_ids = Array.wrap(params[:group_ids])
        ## new group
        unless @group.name.empty?
            if @group.save
                @group_ids << @group.id.to_s
            else
                render 'new'
            end

            ## group logo
            @group_update_data = group_params
            unless params[:group][:photo].nil?
                ## rename figure to avoid overwrite
                if params[:group][:photo].original_filename =~ /.*\.(.*)/
                    @file_name = "id" + @group.id.to_s + "." + $1
                else
                    @file_name = "id" + @group.id.to_s + "." + params[:group][:photo].original_filename
                end

                @stored_file_path = Rails.root.join('public', 'photo', 'groups', @file_name)
                File.open(@stored_file_path, 'wb') do |file|
                    file.write(params[:group][:photo].read)
                end

                @group_update_data['photo'] = @file_name

                unless @group.update(@group_update_data)
                    render 'new'
                end
            end
        end

        
        ## add groups of the store
        unless @group_ids.nil?
            @group_ids = Group.find(@group_ids)
            @store_info.groups = @group_ids
        end
        
        if @store_info.update(@store_info_update_data)
            redirect_to @store_info
        else
            render 'new'
        end

    end

    def show
        @store_info = StoreInfo.find(params[:id])
        # @tags = Tag.joins(:store_infos)
        @tags = Tag.all
    end

    def edit
        if current_user.nil?
            redirect_to store_infos_path
        end

        @store_info = StoreInfo.find(params[:id])
        @groups = Group.all
        @group = Group.new

        # render plain: @groups.inspect
    end

    def update
        @store_info = StoreInfo.find(params[:id])
        @group = Group.new(group_params)
        # render plain: params[:store_info].inspect + params[:group].inspect
        # render plain: @group.inspect + " ||| " + @store_info.inspect

        ## add new group
        @group_ids = nil
        unless @group.name.empty?
            if @group.save
                @group_ids = Array.wrap(params[:group_ids])
                @group_ids << @group.id.to_s
            else
                render 'new'
            end
        end

        ## store logo
        @store_info_update_data = store_info_params
        unless params[:store_info][:photo].nil?
            if params[:store_info][:photo].original_filename =~ /.*\.(.*)/
                @file_name = "id" + @store_info.id.to_s + "." + $1
            else
                @file_name = "id" + @store_info.id.to_s + "." + params[:store_info][:photo].original_filename
            end

            @stored_file_path = Rails.root.join('public', 'photo', 'store_infos', @file_name)
            File.open(@stored_file_path, 'wb') do |file|
                file.write(params[:store_info][:photo].read)
            end

            @store_info_update_data['photo'] = @file_name
        end

        ## update belonging groups
        unless params[:group_ids].nil?
            @group_ids = Group.find(params[:group_ids])
            @store_info.groups = @group_ids
        end
        
        ## update store_info
        if @store_info.update(@store_info_update_data)
            redirect_to @store_info
        else
            render 'edit'
        end
    end

    def index
        @store_info = StoreInfo.all
    end

    def destroy
        @store_info = StoreInfo.find(params[:id])
        
        ## delete logo
        unless @store_info.photo.nil?
            @logo_file = Rails.root.join('public', 'photo', 'store_infos', @store_info.photo)
            File.delete(@logo_file) if File.exist?(@logo_file)
        end
        
        ## delete db entry
        @store_info.destroy

        redirect_to store_infos_path
    end

    def logo
        @store_info = StoreInfo.find(params[:id])
        unless @store_info.photo.nil?
            File.open(Rails.root.join('public', 'photo', 'store_infos', @store_info.photo), 'rb') do |f|
                send_data f.read, :disposition => "inline"
            end
        end
    end

    private
        def store_info_params
            params.require(:store_info).permit(:name, :country, :city, :district, :zip, :street, :phone, :official_site, :rate_reference, :photo)
        end

        def group_params
            params.require(:group).permit(:name, :photo, :store_infos)
        end
end

app/helpers/store_infos_helper.rb
module StoreInfosHelper
end

app/views/store_infos/_form.html.erb
<%= form_for @store_info do |f| %>

  <% if @store_info.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@store_info.errors.count, "error") %> prohibited
        this store from being saved:
      </h2>
      <ul>
        <% @store_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </p>

  <p>
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </p>

  <p>
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :official_site %><br>
    <%= f.text_field :official_site %>
  </p>

  <p>
    <%= f.label :rate_reference %><br>
    <%= f.text_field :rate_reference %>
  </p>

  <p>
    <%= f.label :photo %><br>
    <% unless @store_info.photo.nil? %>
      Old Store Logo:
      <%= image_tag logo_store_info_path(@store_info) %>
      <BR>
    <% end %>
    <%= f.file_field :photo %>
  </p>


  <p>
    <%= f.label :Groups %><br>
    <% @groups.each do |group| %>
    <% checked = @store_info.groups.include?(group) %>
    <%= check_box_tag "group_ids[]", group.id, checked %>
    <%= label_tag(group.id, group.name) %>
    <% end %>
  </p> 


  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this store from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  沒有店家所屬的連集團? <a group-form="show" data-no-turbolink href="#"> 新增一個! </a>  
  <div id="new_group" style="display: none">
    <p>
      <%= fields_for :group, @group do |group_f| %>
      <%= render partial: 'groups/subform', locals: {f: group_f} %>
      <% end %>
    </p> 
  </div>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/store_infos/edit.html.erb
<h1>Editing Store</h1>

<%= render partial: 'form', locals: {current_path: edit_store_info_path}  %>

<%= link_to 'Back', store_infos_path %>

app/views/store_infos/index.html.erb
<h1>Listing stores</h1>

<% unless current_user.nil? %>
    <%= link_to 'New store', new_store_info_path %><BR><BR>
<% end %>


<table>
    <tr>
        <th>Name</th>
        <th>Country</th>
        <th>City</th>
        <th>District</th>
        <th>ZIP</th>
        <th>Street</th>
        <th>Phone</th>
        <th>Site</th>
        <th>Rate Ref</th>
        <th>Photo</th>
    </tr>

    <% @store_info.each do |store_info| %>
        <tr>
            <td><%= store_info.name %></td>
            <td><%= store_info.country %></td>
            <td><%= store_info.city %></td>
            <td><%= store_info.district %></td>
            <td><%= store_info.zip %></td>
            <td><%= store_info.street %></td>
            <td><%= store_info.phone %></td>
            <td><%= store_info.official_site %></td>
            <td><%= store_info.rate_reference %></td>
            <td><%= image_tag logo_store_info_path(store_info) %></td>
            <td><%= link_to 'Show', store_info_path(store_info) %></td>
            <% unless current_user.nil? %>
                <td><%= link_to 'Edit', edit_store_info_path(store_info) %></td>
                <td><%= link_to 'Delete', store_info_path(store_info),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/store_infos/new.html.erb
<h1>New Store</h1>

<%= render partial: 'form', locals: {current_path: new_store_info_path} %>

<%= link_to 'Back', store_infos_path %>

app/views/store_infos/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @store_info.name %>
</p>

<p>
    <strong>Country:</strong>
    <%= @store_info.country %>
</p>

<p>
    <strong>city:</strong>
    <%= @store_info.city %>
</p>

<p>
    <strong>District:</strong>
    <%= @store_info.district %>
</p>

<p>
    <strong>ZIP:</strong>
    <%= @store_info.zip %>
</p>

<p>
    <strong>Street:</strong>
    <%= @store_info.street %>
</p>

<p>
    <strong>Phone:</strong>
    <%= @store_info.phone %>
</p>

<p>
    <strong>Site:</strong>
    <%= @store_info.official_site %>
</p>

<p>
    <strong>Rate Reference:</strong>
    <%= @store_info.rate_reference %>
</p>

<p>
    <strong>Photo:</strong>
    <% unless @store_info.photo.nil? %>
      <%= image_tag logo_store_info_path(@store_info) %>
    <% end %>
</p>

<p>
    <strong>Groups:</strong><BR>
    <% @store_info.groups.each do |group| %>
        <%= group.name %><BR>
    <% end %>
</p>


<h2>Tags:</h2>
<%= render "tags/store_info_tag" %>

<h2>Add tags:</h2>
<%= render 'tags/store_info_form' %>


<h2>Ratings:</h2>
<%= render "store_info_ratings/store_info_rating" %>

<% unless @store_info.users.include?(current_user) %>
  <h2>Add Comment:</h2>
  <%= render 'store_info_ratings/form' %>
<% end %>


<% unless current_user.nil? %>
    <%= link_to 'Edit', edit_store_info_path(@store_info) %> |
<% end %>
<%= link_to 'Back', store_infos_path %>