config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'profile/show' => 'users#show', as: 'show_profile'
  get 'profile/edit' => 'users#edit', as: 'edit_profile'
  match 'profile/update' => 'users#update', as: 'update_profile', via: [:patch]

  get 'admin/list_users' => 'admin#list_users', as: 'admin_list_users'
  get 'admin/show_user' => 'admin#show_user', as: 'admin_show_user'
  get 'admin/edit_user/:id' => 'admin#edit_user', as: 'admin_edit_user'
  match 'admin/update_user/:id' => 'admin#update_user', as: 'admin_update_user', via: [:patch]
  match 'admin/delete_user/:id' => 'admin#delete_user', as: 'admin_delete_user', via: [:delete]

  resources :wallets

  resources :groups do
    member do
      get 'logo'
    end
  end

  resources :store_infos do
    resources :tags
    resources :store_info_ratings

    member do
      get 'logo'
    end
  end

  resources :agents
  resources :card_types
  resources :card_levels
  resources :banks
  resources :cards do
    resources :tags
    resources :card_ratings
  end

  resources :discounts do
    resources :tags
    resources :discount_ratings
  end

  root to: "welcome#index"
end

app/models/agent.rb
class Agent < ActiveRecord::Base
    has_many :card_levels, dependent: :destroy
    validates :name, presence: true
    validates_uniqueness_of :name
end

app/models/bank.rb
class Bank < ActiveRecord::Base
	has_many :cards, dependent: :destroy
	validates :name, presence: true
	validates_uniqueness_of :name

	def name_with_swift_number
		"#{swift_number} #{name}"
	end
end

app/models/card.rb
class Card < ActiveRecord::Base
    belongs_to :bank
    belongs_to :card_type
    belongs_to :card_level

    has_many :wallets
    has_many :users, :through => :wallets

    has_many :tag_sets, dependent: :destroy
    has_many :tags, :through => :tag_sets

    has_many :card_ratings, dependent: :destroy
    has_many :rating_users, :through => :card_ratings, :source => :user

    validates :name, presence: true

    def full_name
        @full_name = "#{self.name} - "

        unless bank.nil?
            @full_name += "#{bank.name}, "
        end

        unless card_level.nil?
            @full_name += "#{card_level.name_with_agent}, "
        end

        unless card_type.nil?
            @full_name += "#{card_type.name}"
        end

        return @full_name
    end
end

app/models/card_level.rb
class CardLevel < ActiveRecord::Base
    has_many :cards, dependent: :destroy
    belongs_to :agent
    validates :name, presence: true
    validates :level, presence: true
    validates_uniqueness_of :level, scope: :agent_id

    def name_with_agent
        if agent.nil?
            "#{name}"
        else
            "#{agent.name} #{name}"
        end
    end
end

app/models/card_rating.rb
class CardRating < ActiveRecord::Base
  belongs_to :card
  belongs_to :user
end

app/models/card_type.rb
class CardType < ActiveRecord::Base
    has_many :cards, dependent: :destroy
    validates :name, presence: true
    validates_uniqueness_of :name
end

app/models/click.rb
class Click < ActiveRecord::Base
end

app/models/discount.rb
class Discount < ActiveRecord::Base
    belongs_to :group
    belongs_to :store_info

    has_many :discount_requirement_sets, dependent: :destroy
    accepts_nested_attributes_for :discount_requirement_sets, :reject_if => lambda { |a| a[:bank_id].blank? && a[:card_id].blank? && a[:card_level_id].blank?}, :allow_destroy => true
    has_many :banks, :through => :discount_requirement_sets
    has_many :cards, :through => :discount_requirement_sets
    has_many :card_levels, :through => :discount_requirement_sets

    has_many :tag_sets, dependent: :destroy
    has_many :tags, :through => :tag_sets
    # accepts_nested_attributes_for :tags, :reject_if => lambda { |a| a[:name].blank?}, :allow_destroy => true

    has_many :discount_ratings, dependent: :destroy
    has_many :users, :through => :discount_ratings
    
    # validates :complete_description, presence: true
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :group_sets, dependent: :destroy
    has_many :store_infos, :through => :group_sets
    validates :name, presence: true
end

app/models/group_set.rb
class GroupSet < ActiveRecord::Base
    belongs_to :group
    belongs_to :store_info
end

app/models/store_info.rb
class StoreInfo < ActiveRecord::Base
    has_many :group_sets, dependent: :destroy
    has_many :groups, :through => :group_sets
    
    has_many :store_info_ratings, dependent: :destroy
    has_many :users, :through => :store_info_ratings

    has_many :tag_sets, dependent: :destroy
    has_many :tags, :through => :tag_sets

    validates :name, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :tag_sets, dependent: :destroy
    has_many :discounts, :through => :tag_sets
    has_many :store_infos, :through => :tag_sets
    has_many :cards, :through => :tag_sets
    
    validates :name, presence: true
end

app/models/tag_set.rb
class TagSet < ActiveRecord::Base
    belongs_to :tag
    belongs_to :discount
    belongs_to :store_info
    belongs_to :card
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         #, :authentication_keys => [:login]

  has_many :wallets, dependent: :destroy
  has_many :cards, :through => :wallets

  has_many :discount_ratings, dependent: :destroy
  has_many :discounts, :through => :discount_ratings

  has_many :store_info_ratings, dependent: :destroy
  has_many :store_infos, :through => :store_info_ratings

  # Virtual attribute for authenticating by either account or email
  # This is in addition to a real persisted field like 'account'
  # attr_accessor :login
  # def login=(login)
  #   @login = login
  # end

  # def login
  #   @login || self.account || self.email
  # end
end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
    belongs_to :user
    belongs_to :card
end

app/controllers/card_levels_controller.rb
class CardLevelsController < ApplicationController
    def new
        if current_user.nil?
            redirect_to card_levels_path
        end

        @card_level = CardLevel.new
        @agents = Agent.all
    end

    def create
        # render plain: params[:card_level].inspect
        @card_level = CardLevel.new(card_level_params)

        if @card_level.save
            redirect_to @card_level
        else
            render 'new'
        end
        
    end

    def show
        @card_level = CardLevel.find(params[:id])
    end

    def edit
        if current_user.nil?
            redirect_to card_levels_path
        end
        
        @card_level = CardLevel.find(params[:id])
        @agents = Agent.all
    end

    def update
        @card_level = CardLevel.find(params[:id])

        if @card_level.update(card_level_params)
            redirect_to @card_level
        else
            render 'edit'
        end
    end

    def index
        @card_level = CardLevel.all
    end

    def destroy
        @card_level = CardLevel.find(params[:id])
        @card_level.destroy

        redirect_to card_levels_path
    end

    private
        def card_level_params
            params.require(:card_level).permit(:level, :name, :agent_id)
        end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/card_levels_helper.rb
module CardLevelsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card_levels/_form.html.erb
<%= form_for @card_level do |f| %>

    <% if @card_level.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@card_level.errors.count, "error") %> prohibited
                this card_level from being saved:
            </h2>
            <ul>
                <% @card_level.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= f.label :Level %><br>
        <%= f.text_field :level %>
    </p>

    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :機構 %><br>
        <%= f.collection_select :agent_id, Agent.order(:name),:id,:name, include_blank: true %>
    </p>

    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/card_levels/edit.html.erb
<h1>Editing Card Level</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', card_levels_path %>

app/views/card_levels/index.html.erb
<h1>Listing card_levels</h1>

<% unless current_user.nil? %>
    <%= link_to 'New Card Level', new_card_level_path %> <BR><BR>
<% end %>

<table>
    <tr>
        <th>等級</th>
        <th>卡別</th>
        <th>機構</th>
    </tr>

    <% @card_level.each do |card_level| %>
        <tr>
            <td><%= card_level.level %></td>
            <td><%= card_level.name %></td>
            <td>
                <% unless card_level.agent_id.nil? %>
                    <%= card_level.agent.name %>
                <% end %>
            </td>
            <td><%= link_to 'Show', card_level_path(card_level) %></td>
            <% unless current_user.nil? %>
                <td><%= link_to 'Edit', edit_card_level_path(card_level) %></td>
                <td><%= link_to 'Delete', card_level_path(card_level),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/card_levels/new.html.erb
<h1>New Card Level</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', card_levels_path %>

app/views/card_levels/show.html.erb
<p>
    <strong>Level:</strong>
    <%= @card_level.level %>
</p>

<p>
    <strong>Name:</strong>
    <%= @card_level.name %>
</p>

<p>
    <strong>Agent:</strong>
    <% unless @card_level.agent.nil? %> 
        <%= @card_level.agent.name %>
    <% end %>
</p>


<% unless current_user.nil? %>
    <%= link_to 'Edit', edit_card_level_path(@card_level) %> |
<% end %>
<%= link_to 'Back', card_levels_path %>