config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'profile/show' => 'users#show', as: 'show_profile'
  get 'profile/edit' => 'users#edit', as: 'edit_profile'
  match 'profile/update' => 'users#update', as: 'update_profile', via: [:patch]

  get 'admin/list_users' => 'admin#list_users', as: 'admin_list_users'
  get 'admin/show_user' => 'admin#show_user', as: 'admin_show_user'
  get 'admin/edit_user/:id' => 'admin#edit_user', as: 'admin_edit_user'
  match 'admin/update_user/:id' => 'admin#update_user', as: 'admin_update_user', via: [:patch]
  match 'admin/delete_user/:id' => 'admin#delete_user', as: 'admin_delete_user', via: [:delete]

  resources :wallets

  resources :groups do
    member do
      get 'logo'
    end
  end

  resources :store_infos do
    resources :tags
    resources :store_info_ratings

    member do
      get 'logo'
    end
  end

  resources :agents
  resources :card_types
  resources :card_levels
  resources :banks
  resources :cards do
    resources :tags
    resources :card_ratings
  end

  resources :discounts do
    resources :tags
    resources :discount_ratings
  end

  root to: "welcome#index"
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :group_sets, dependent: :destroy
    has_many :store_infos, :through => :group_sets
    validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def new
        if current_user.nil? 
            redirect_to groups_path
        end

        @group = Group.new
        @store_infos = StoreInfo.all
    end

    def create
        # render plain: params[:group].inspect

        @group_update_data = group_params
        @group_update_data['photo'] = nil
        @group = Group.new(@group_update_data)
        ## save to get id
        unless @group.save
            render 'new'
        end

        
        ## logo
        @group_update_data = group_params
        unless params[:group][:photo].nil?
            ## rename figure to avoid overwrite
            if params[:group][:photo].original_filename =~ /.*\.(.*)/
                @file_name = "id" + @group.id.to_s + "." + $1
            else
                @file_name = "id" + @group.id.to_s + "." + params[:group][:photo].original_filename
            end

            @stored_file_path = Rails.root.join('public', 'photo', 'groups', @file_name)
            File.open(@stored_file_path, 'wb') do |file|
                file.write(params[:group][:photo].read)
            end

            @group_update_data['photo'] = @file_name
        end
        
        ## belonging stores
        unless params[:store_info_ids].nil?
            @store_info_ids = StoreInfo.find(params[:store_info_ids])
            @group.store_infos = @store_info_ids
        end

        if @group.update(@group_update_data)
            redirect_to @group
        else
            render 'new'
        end
        
    end

    def show
        @group = Group.find(params[:id])
    end

    def edit
        if current_user.nil? 
            redirect_to groups_path
        end

        @group = Group.find(params[:id])
        @store_infos = StoreInfo.all
    end

    def update
        @group = Group.find(params[:id])
        
        unless params[:store_info_ids].nil?
            @store_info_ids = StoreInfo.find(params[:store_info_ids])
            @group.store_infos = @store_info_ids
        end

        @group_update_data = group_params
        unless params[:group][:photo].nil?
            if params[:group][:photo].original_filename =~ /.*\.(.*)/
                @file_name = "id" + @group.id.to_s + "." + $1
            else
                @file_name = "id" + @group.id.to_s + "." + params[:group][:photo].original_filename
            end
            
            @stored_file_path = Rails.root.join('public', 'photo', 'groups', @file_name)
            File.open(@stored_file_path, 'wb') do |file|
                file.write(params[:group][:photo].read)
            end

            @group_update_data['photo'] = @file_name
        end

        
        if @group.update(@group_update_data)
            redirect_to @group
        else
            render 'edit'
        end
    end

    def index
        @group = Group.all
    end

    def destroy
        @group = Group.find(params[:id])

        ## delete logo
        unless @group.photo.nil?
            @logo_file = Rails.root.join('public', 'photo', 'groups', @group.photo)
            File.delete(@logo_file) if File.exist?(@logo_file)
        end

        ## delete db entry
        @group.destroy

        redirect_to groups_path
    end

    def logo
        @group = Group.find(params[:id])
        unless @group.photo.nil?
            File.open(Rails.root.join('public', 'photo', 'groups', @group.photo), 'rb') do |f|
                send_data f.read, :disposition => "inline"
            end
        end
    end

    private
        def group_params
            params.require(:group).permit(:name, :photo, :store_infos)
        end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>

<% if @group.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@group.errors.count, "error") %> prohibited
    this group from being saved:
  </h2>
  <ul>
    <% @group.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= render partial: 'subform', locals: {f: f} %>

<p>
  <%= f.label :Stores %><br>
  <% @store_infos.each do |store_info| %>
  <% checked = @group.store_infos.include?(store_info) %>
  <%= check_box_tag "store_info_ids[]", store_info.id, checked %>
  <%= label_tag(store_info.id, store_info.name) %>
  <% end %>
</p>


<p>
  <%= f.submit %>
</p>

<% end %>

app/views/groups/_subform.html.erb
<p>
  <%= f.label :group_name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :group_photo %><br>
  <% unless @group.photo.nil? %>
    Old Logo:
    <%= image_tag logo_group_path(@group) %>
    <BR>
  <% end %>

  <%= f.file_field :photo %>
</p>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<% unless current_user.nil? %>
    <%= link_to 'New group', new_group_path %> <BR><BR>
<% end %>


<table>
    <tr>
        <th>Name</th>
        <th>Photo</th>
    </tr>

    <% @group.each do |group| %>
        <tr>
            <td><%= group.name %></td>
            <td>
                <%= image_tag logo_group_path(group) %>
            </td>
            <td><%= link_to 'Show', group_path(group) %></td>
            <% unless current_user.nil? %>
                <td><%= link_to 'Edit', edit_group_path(group) %></td>
                <td><%= link_to 'Delete', group_path(group),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @group.name %>
</p>
 
<p>
    <strong>Photo:</strong>
    <%= image_tag logo_group_path(@group) %>
</p>

<p>
    <strong>Stores:</strong><BR>
    <% @group.store_infos.each do |store| %>
        <%= store.name %><BR>
    <% end %>
</p>


<% unless current_user.nil? %>
    <%= link_to 'Edit', edit_group_path(@group) %> |
<% end %>
<%= link_to 'Back', groups_path %>